# Generated by Django 5.2.3 on 2025-06-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_appeal_responder'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('chairman', 'Председатель'), ('board_member', 'Член правления')], default='user', max_length=20),
        ),
    ]
