# Generated by Django 5.2.3 on 2025-06-24 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('charter', 'Уставные документы'), ('meeting_minutes', 'Протоколы собраний'), ('report', 'Отчёты'), ('internal_rules', 'Правила внутреннего распорядка'), ('other', 'Другая нормативная документация')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='community_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='garden.community')),
            ],
        ),
    ]
