# Generated by Django 5.2.3 on 2025-06-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairman', 'Председатель правления'), ('treasurer', 'Казначей'), ('board_member', 'Член правления'), ('electricity_manager', 'Ответственный за электрохозяйство'), ('water_manager', 'Ответственный за водохозяйство')], max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('plot_number', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='garden.community')),
            ],
        ),
    ]
