# Generated by Django 5.2.3 on 2025-06-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_boardmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Размер членских взносов')),
                ('membership_fee_due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты членских взносов')),
                ('membership_fee_instruction', models.TextField(blank=True, verbose_name='Инструкция по оплате взносов')),
                ('additional_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Размер дополнительных взносов')),
                ('additional_fee_due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты дополнительных взносов')),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='garden.community')),
            ],
        ),
    ]
