# Generated by Django 5.2.3 on 2025-07-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0010_rename_content_advertisement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='Контакт для связи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='garden.community'),
        ),
    ]
