# Generated by Django 5.2.3 on 2025-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0012_document_is_deleted_documentfolder_document_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='community',
            name='bank_details',
            field=models.TextField(blank=True, null=True, verbose_name='Банковские реквизиты'),
        ),
        migrations.AddField(
            model_name='community',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='community',
            name='postal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('charter', 'Уставные документы'), ('meeting_minutes', 'Протоколы собраний'), ('report', 'Отчёты'), ('internal_rules', 'Правила внутреннего распорядка'), ('other', 'Другая нормативная документация')], max_length=20, verbose_name='тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Описание новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
