# Generated by Django 5.2.3 on 2025-07-16 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0014_alter_vote_choice_alter_vote_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания голосования'),
        ),
        migrations.AddField(
            model_name='voting',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала голосования'),
        ),
    ]
