# Generated by Django 5.2.3 on 2025-07-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0015_voting_end_date_voting_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
