# Generated by Django 5.2.3 on 2025-07-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0016_forumpost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_vote',
            field=models.BooleanField(default=True, verbose_name='Разрешено голосовать'),
        ),
    ]
