# Generated by Django 5.2.3 on 2025-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0017_profile_can_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
