# Generated by Django 5.2.3 on 2025-08-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0018_profile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='plot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
