# Generated by Django 5.2.3 on 2025-08-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0019_alter_boardmember_full_name_alter_boardmember_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='plot_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
