# Generated by Django 5.2.3 on 2025-08-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0021_boardmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='additional_fee_instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
