# Generated by Django 5.2.3 on 2025-08-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0022_paymentinfo_additional_fee_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='messenger_group_link',
            field=models.URLField(blank=True, help_text='Ссылка на группу Viber или другую мессенджер-группу.', max_length=400, null=True, verbose_name='Ссылка на группу в мессенджере'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='additional_fee_instruction',
            field=models.TextField(blank=True, default='', verbose_name='Информация и инструкция по оплате взносов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='membership_fee_instruction',
            field=models.TextField(blank=True, verbose_name='Информация и инструкция по оплате взносов'),
        ),
    ]
