# Generated by Django 5.2.3 on 2025-08-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0023_community_messenger_group_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfolder',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
