# Generated by Django 5.2.3 on 2025-08-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0024_alter_documentfolder_options_documentfolder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='topic',
            field=models.CharField(choices=[('sale_rent', 'Продажа/аренда участков'), ('services', 'Услуги'), ('equipment', 'Техника'), ('materials', 'Материалы'), ('garden', 'Сад и огород'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тема объявления'),
            preserve_default=False,
        ),
    ]
