# Generated by Django 5.2.3 on 2025-08-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0025_advertisement_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='garden.community', verbose_name='Товарищество'),
            preserve_default=False,
        ),
    ]
