# Generated by Django 5.2.3 on 2025-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0026_advertisement_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
