# Generated by Django 5.2.3 on 2025-08-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0027_news_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно на сайте'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Описание новости '),
        ),
    ]
