# Generated by Django 5.2.3 on 2025-08-31 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0028_community_is_active_alter_news_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.TextField(verbose_name='Повестка дня общего собрания')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Порядок заполнения бюллетеня')),
                ('submission_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место представления заполненных бюллетеней')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('counting_commission_date', models.DateField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='ballot_docs/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.community')),
            ],
        ),
        migrations.CreateModel(
            name='BallotQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('decision_project', models.TextField(verbose_name='Проект решения')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='garden.ballot')),
            ],
        ),
        migrations.CreateModel(
            name='BallotVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('for', 'За'), ('against', 'Против'), ('abstained', 'Воздержался')], max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='garden.ballotquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('question', 'user')},
            },
        ),
    ]
